apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: {{ include "hello-world-service.fullname" . }}
spec:
  prefix: /api/hello-world-service/
  service: {{ .Values.namespace }}.{{ .Chart.Name }}
  resolver: consul-dc1
  load_balancer:
    policy: round_robin
